/*
 * deck-builder.js — turns extracted PPTX content + user options into ONE
 * self-contained HTML slideshow string (no external requests, works from
 * file://, survives email). Layout contract follows the project spec:
 * stacked full-screen <section class="slide">, one .active, fade transition,
 * a single showSlide(n) engine, keyboard/touch/button navigation, counters,
 * CSS-variable theme, optional animated canvas gated per slide via data-bg.
 *
 *   DeckBuilder.build(content, options) → html string
 *
 * All slide text is HTML-escaped at extraction time (runs) or here (titles,
 * cells); the only markup that reaches the file is generated by this module.
 */
(function (global) {
  'use strict';

  var esc = function (s) {
    return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

  var FONTS = {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    serif: "'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, 'Times New Roman', serif",
    mono: "'Cascadia Code', Consolas, 'SF Mono', Menlo, 'Courier New', monospace"
  };

  var DEFAULTS = {
    mode: 'faithful',                    // faithful (original layout) | restyle
    title: 'Slideshow',
    theme: {
      bg: '#0b1220', bg2: '#101a30', text: '#e8eefc', muted: '#93a4c4',
      accent: '#4da8ff', accent2: '#7ab4ff'
    },
    font: 'sans',
    transition: 'fade',                  // fade | slide | zoom | none
    nav: {
      placement: 'bc',                   // bc | bl | br | tr
      shape: 'pill',                     // pill | round | square
      opacity: 0.85,                     // resting opacity 0.2..1
      labels: 'arrows',                  // arrows | words
      showCounter: true,                 // counter between the buttons
      showTopCounter: true               // counter pinned top-right
    },
    progressBar: true,
    effect: 'radar',                     // id from Backgrounds registry | 'none'
    effectShow: 'title-subtle',          // title | title-subtle | all
    effectIntensity: 0.7,                // 0.2 .. 1
    flairUnderline: true,
    flairCorners: true,
    includeNotes: true
  };

  function merge(base, over) {
    var out = {};
    for (var k in base) {
      if (base[k] && typeof base[k] === 'object' && !Array.isArray(base[k])) {
        out[k] = merge(base[k], (over || {})[k] || {});
      } else {
        out[k] = over && over[k] !== undefined ? over[k] : base[k];
      }
    }
    return out;
  }

  // ---------------------------------------------------------------- blocks

  function bulletsHtml(items) {
    var out = '<ul class="bullets">';
    items.forEach(function (it) {
      var lvl = Math.min(it.level || 0, 4);
      if (it.noBullet) {
        out += '<li class="plain lvl' + lvl + '">' + it.html + '</li>';
      } else {
        out += '<li class="lvl' + lvl + '">' + it.html + '</li>';
      }
    });
    return out + '</ul>';
  }

  function tableHtml(block) {
    var rows = block.rows;
    var html = '<div class="tbl-wrap"><table>';
    rows.forEach(function (r, i) {
      var tag = (i === 0 && block.headerRow) ? 'th' : 'td';
      html += '<tr>';
      r.forEach(function (c) { html += '<' + tag + '>' + esc(c) + '</' + tag + '>'; });
      html += '</tr>';
    });
    return html + '</table></div>';
  }

  function stubHtml(label) {
    var icon = /chart/i.test(label) ? '📊' : /smartart|diagram/i.test(label) ? '🧩' : '🖼';
    return '<div class="stub">' + icon + ' ' + esc(label) +
      '<span class="stub-note">from the original deck</span></div>';
  }

  function blocksHtml(blocks) {
    var html = '', i = 0;
    while (i < blocks.length) {
      var b = blocks[i];
      if (b.kind === 'image') {
        // group consecutive images into one row
        var imgs = [];
        while (i < blocks.length && blocks[i].kind === 'image') { imgs.push(blocks[i]); i++; }
        html += '<div class="media-row n' + Math.min(imgs.length, 3) + '">';
        imgs.forEach(function (im) {
          html += '<figure><img src="' + im.src + '" alt="' + esc(im.name) + '"></figure>';
        });
        html += '</div>';
        continue;
      }
      if (b.kind === 'bullets') html += bulletsHtml(b.items);
      else if (b.kind === 'table') html += tableHtml(b);
      else if (b.kind === 'stub') html += stubHtml(b.label);
      i++;
    }
    return html;
  }

  function cornersHtml() {
    return '<div class="corner tl"></div><div class="corner tr"></div>' +
           '<div class="corner bl"></div><div class="corner br"></div>';
  }

  function slideHtml(slide, idx, opt, dataBg) {
    var cls = 'slide s-' + slide.type + (idx === 0 ? ' active' : '');
    var html = '<section class="' + cls + '" data-bg="' + dataBg + '">';
    if (slide.type === 'title') {
      html += '<div class="wrap center">';
      if (opt.flairCorners) html += cornersHtml();
      html += '<h1>' + esc(slide.title || opt.title) + '</h1>';
      if (slide.subtitle) html += '<p class="subtitle">' + esc(slide.subtitle).replace(/\n/g, '<br>') + '</p>';
      html += blocksHtml(slide.blocks);
      html += '</div>';
    } else if (slide.type === 'section') {
      html += '<div class="wrap center">';
      html += '<div class="section-num">' + String(idx + 1).padStart(2, '0') + '</div>';
      html += '<h2 class="section-title">' + esc(slide.title || '') + '</h2>';
      html += blocksHtml(slide.blocks);
      html += '</div>';
    } else {
      html += '<div class="wrap">';
      if (slide.title) html += '<h2>' + esc(slide.title) + '</h2>';
      if (slide.subtitle) html += '<p class="subtitle small">' + esc(slide.subtitle) + '</p>';
      html += '<div class="content">' + blocksHtml(slide.blocks) + '</div>';
      html += '</div>';
    }
    return html + '</section>';
  }

  // -------------------------------------------------- faithful-mode pieces

  // Slide-content styles the legacy renderer's markup relies on
  // (adapted from the original project's pptx2html.css, scoped to .pslide).
  var PSLIDE_CSS = [
    '.pslide{position:relative;text-align:center;overflow:hidden;flex:none;',
    '  border-radius:8px;box-shadow:0 26px 90px rgba(0,0,0,.5);',
    '  transform:scale(var(--pscale,1));transform-origin:center center}',
    '.pslide div.block{position:absolute;top:0;left:0;width:100%}',
    '.pslide div.content{display:flex;flex-direction:column}',
    '.pslide div.v-up{justify-content:flex-start}',
    '.pslide div.v-mid{justify-content:center}',
    '.pslide div.v-down{justify-content:flex-end}',
    '.pslide div.h-left{align-items:flex-start;text-align:left}',
    '.pslide div.h-mid{align-items:center;text-align:center}',
    '.pslide div.h-right{align-items:flex-end;text-align:right}',
    '.pslide div.up-left{justify-content:flex-start;align-items:flex-start;text-align:left}',
    '.pslide div.up-center{justify-content:flex-start;align-items:center}',
    '.pslide div.up-right{justify-content:flex-start;align-items:flex-end}',
    '.pslide div.center-left{justify-content:center;align-items:flex-start;text-align:left}',
    '.pslide div.center-center{justify-content:center;align-items:center}',
    '.pslide div.center-right{justify-content:center;align-items:flex-end}',
    '.pslide div.down-left{justify-content:flex-end;align-items:flex-start;text-align:left}',
    '.pslide div.down-center{justify-content:flex-end;align-items:center}',
    '.pslide div.down-right{justify-content:flex-end;align-items:flex-end}',
    '.pslide table{position:absolute;border-collapse:collapse}',
    '.pslide table,.pslide th,.pslide td{border:1px solid black}',
    '.pslide svg.drawing{position:absolute;overflow:visible}',
    '.slide.s-faithful{padding:0}'
  ].join('\n');

  function faithfulCss(faithful) {
    var out = PSLIDE_CSS + '\n' + (faithful.globalCss || '');
    if (faithful.hasCharts && global.NV_D3_CSS) out += '\n' + global.NV_D3_CSS;
    return out;
  }

  function faithfulFitJs(slideSize) {
    return [
      'var PW=' + Math.round(slideSize.width) + ',PH=' + Math.round(slideSize.height) + ';',
      'function fitSlides(){',
      '  var s=Math.min((window.innerWidth-60)/PW,(window.innerHeight-110)/PH);',
      '  document.documentElement.style.setProperty("--pscale",Math.min(s,2.2));',
      '}',
      'window.addEventListener("resize",fitSlides);',
      'fitSlides();'
    ].join('\n');
  }

  // ------------------------------------------------------------------ CSS

  function css(opt, hasCanvas, hasNotes) {
    var t = opt.theme;
    var fxSubtle = (0.22 * opt.effectIntensity).toFixed(3);
    var fxFeature = (0.42 + 0.38 * opt.effectIntensity).toFixed(3);
    var navPos = {
      bc: 'left:50%;transform:translateX(-50%);bottom:22px;',
      bl: 'left:22px;bottom:22px;',
      br: 'right:22px;bottom:22px;',
      tr: 'right:22px;top:18px;'
    }[opt.nav.placement] || 'left:50%;transform:translateX(-50%);bottom:22px;';
    var btnRadius = opt.nav.shape === 'round' ? '50%' : opt.nav.shape === 'square' ? '8px' : '999px';
    var btnPad = opt.nav.labels === 'words' ? '10px 18px' : (opt.nav.shape === 'round' ? '0' : '10px 14px');

    var transitions = {
      fade: '@keyframes slideIn{from{opacity:0}to{opacity:1}}',
      slide: '@keyframes slideIn{from{opacity:0;transform:translateX(48px)}to{opacity:1;transform:translateX(0)}}',
      zoom: '@keyframes slideIn{from{opacity:0;transform:scale(.955)}to{opacity:1;transform:scale(1)}}',
      none: ''
    };
    // The fade rides on a temporary .anim class (added per slide change,
    // removed by a timer) so a slide is NEVER invisible just because the
    // animation clock is throttled (background tabs, embeds, screenshots).
    var slideAnim = opt.transition === 'none' ? '' :
      '.slide.active.anim{animation:slideIn .55s cubic-bezier(.22,.8,.3,1) both}';

    return [
      ':root{',
      '  --bg:' + t.bg + ';--bg2:' + t.bg2 + ';--text:' + t.text + ';--muted:' + t.muted + ';',
      '  --accent:' + t.accent + ';--accent2:' + t.accent2 + ';',
      '  --nav-opacity:' + opt.nav.opacity + ';--fx-subtle:' + fxSubtle + ';--fx-feature:' + fxFeature + ';',
      '}',
      '*{margin:0;padding:0;box-sizing:border-box}',
      'html,body{height:100%;overflow:hidden}',
      'body{background:radial-gradient(120% 130% at 50% 0%, var(--bg2) 0%, var(--bg) 58%);',
      '  color:var(--text);font-family:' + FONTS[opt.font] + ';-webkit-font-smoothing:antialiased}',
      'a{color:var(--accent2)}',
      '::selection{background:var(--accent);color:var(--bg)}',
      hasCanvas ? '#bg-canvas{position:fixed;inset:0;z-index:0;pointer-events:none;opacity:var(--fx-subtle);transition:opacity .9s ease}' : '',
      hasCanvas ? '#bg-canvas.feature{opacity:var(--fx-feature)}#bg-canvas.hidden{opacity:0}' : '',
      transitions[opt.transition] || transitions.fade,
      '.slide{position:fixed;inset:0;width:100vw;height:100vh;display:none;z-index:1;',
      '  align-items:center;justify-content:center;padding:4vh 5vw}',
      '.slide.active{display:flex}',
      slideAnim,
      '.wrap{max-width:1080px;width:100%;position:relative}',
      '.wrap.center{text-align:center}',
      /* ----- typography ----- */
      'h1{font-size:clamp(2.3rem,6.5vw,5rem);line-height:1.08;letter-spacing:-.015em;font-weight:700}',
      '.s-title .subtitle{margin-top:26px;font-size:clamp(1.1rem,2.4vw,1.6rem);color:var(--muted);font-weight:300}',
      '.subtitle.small{margin-top:6px;color:var(--muted);font-size:clamp(1rem,1.8vw,1.2rem)}',
      'h2{font-size:clamp(1.6rem,3.6vw,2.7rem);line-height:1.15;font-weight:650;letter-spacing:-.01em}',
      '.section-num{font-size:clamp(.95rem,1.6vw,1.15rem);letter-spacing:.45em;color:var(--accent);margin-bottom:18px;font-weight:600}',
      '.section-title{font-size:clamp(2.1rem,5vw,3.8rem)}',
      opt.flairUnderline ? [
        '.s-content h2::after,.s-image h2::after,.s-table h2::after{content:"";display:block;width:0;height:3px;',
        '  background:linear-gradient(90deg,var(--accent),transparent);border-radius:2px;margin-top:12px}',
        '.slide.active h2::after{animation:grow .7s .15s cubic-bezier(.22,.8,.3,1) forwards}',
        '@keyframes grow{to{width:84px}}',
        '.s-title h1::after,.s-section .section-title::after{content:"";display:block;width:0;height:3px;margin:22px auto 0;',
        '  background:linear-gradient(90deg,transparent,var(--accent),transparent);border-radius:2px}',
        '.s-title.active h1::after,.s-section.active .section-title::after{animation:growC .8s .2s cubic-bezier(.22,.8,.3,1) forwards}',
        '@keyframes growC{to{width:150px}}'
      ].join('\n') : '',
      /* ----- content blocks ----- */
      '.content{margin-top:30px}',
      '.bullets{list-style:none;text-align:left;display:grid;gap:14px;margin-top:8px}',
      '.bullets li{font-size:clamp(1.05rem,2.1vw,1.45rem);line-height:1.5;padding-left:1.5em;position:relative;color:var(--text)}',
      '.bullets li::before{content:"\\25B8";position:absolute;left:.2em;color:var(--accent)}',
      '.bullets li.plain::before{content:""}',
      '.bullets li.lvl1{margin-left:1.6em;font-size:clamp(.98rem,1.9vw,1.3rem)}',
      '.bullets li.lvl1::before{content:"\\2022";color:var(--accent2)}',
      '.bullets li.lvl2,.bullets li.lvl3,.bullets li.lvl4{margin-left:3em;font-size:clamp(.92rem,1.7vw,1.18rem);color:var(--muted)}',
      '.bullets li.lvl2::before,.bullets li.lvl3::before,.bullets li.lvl4::before{content:"\\2013";color:var(--accent2)}',
      '.wrap.center .bullets{justify-items:center;text-align:center}',
      '.wrap.center .bullets li{padding-left:0}',
      '.wrap.center .bullets li::before{content:""}',
      '.media-row{display:flex;gap:20px;justify-content:center;align-items:center;flex-wrap:wrap;margin-top:26px}',
      '.media-row figure{flex:0 1 auto;min-width:0}',
      '.media-row.n2 figure,.media-row.n3 figure{flex:1 1 0}',
      '.media-row img{max-width:min(80vw,980px);max-height:54vh;width:auto;height:auto;display:block;margin:auto;',
      '  border-radius:14px;box-shadow:0 18px 50px rgba(0,0,0,.42);border:1px solid color-mix(in srgb,var(--accent) 24%,transparent)}',
      '.media-row.n2 img,.media-row.n3 img{max-width:100%}',
      '.tbl-wrap{margin-top:26px;overflow:auto;max-height:62vh;border-radius:14px;',
      '  border:1px solid color-mix(in srgb,var(--accent) 22%,transparent)}',
      'table{border-collapse:collapse;width:100%;font-size:clamp(.9rem,1.7vw,1.15rem)}',
      'th{background:color-mix(in srgb,var(--accent) 18%,transparent);color:var(--text);font-weight:650}',
      'th,td{padding:12px 18px;text-align:left;border-bottom:1px solid color-mix(in srgb,var(--accent) 14%,transparent)}',
      'tr:last-child td{border-bottom:none}',
      'td{color:color-mix(in srgb,var(--text) 88%,var(--muted))}',
      '.stub{display:inline-flex;align-items:center;gap:10px;margin-top:26px;padding:14px 22px;border-radius:12px;',
      '  border:1.5px dashed color-mix(in srgb,var(--accent) 45%,transparent);color:var(--muted);font-size:1rem}',
      '.stub-note{font-size:.8rem;opacity:.65}',
      /* ----- title corners ----- */
      opt.flairCorners ? [
        '.corner{position:absolute;width:34px;height:34px;border:2.5px solid var(--accent);opacity:.65}',
        '.corner.tl{top:-26px;left:-8px;border-right:none;border-bottom:none;border-radius:6px 0 0 0}',
        '.corner.tr{top:-26px;right:-8px;border-left:none;border-bottom:none;border-radius:0 6px 0 0}',
        '.corner.bl{bottom:-26px;left:-8px;border-right:none;border-top:none;border-radius:0 0 0 6px}',
        '.corner.br{bottom:-26px;right:-8px;border-left:none;border-top:none;border-radius:0 0 6px 0}'
      ].join('\n') : '',
      /* ----- navigation ----- */
      '.navbar{position:fixed;' + navPos + 'z-index:10;display:flex;align-items:center;gap:14px;',
      '  opacity:var(--nav-opacity);transition:opacity .25s ease}',
      '.navbar:hover{opacity:1}',
      '.navbar button{display:inline-flex;align-items:center;justify-content:center;gap:8px;cursor:pointer;',
      '  font:inherit;font-size:.95rem;font-weight:600;color:var(--text);',
      '  background:color-mix(in srgb,var(--bg2) 72%,transparent);',
      '  border:1px solid color-mix(in srgb,var(--accent) 38%,transparent);',
      '  backdrop-filter:blur(8px);border-radius:' + btnRadius + ';padding:' + btnPad + ';',
      (opt.nav.shape === 'round' ? '  width:46px;height:46px;' : '  height:44px;'),
      '  transition:border-color .2s,background .2s,transform .15s}',
      '.navbar button:hover:not(:disabled){border-color:var(--accent);background:color-mix(in srgb,var(--accent) 16%,var(--bg2));transform:translateY(-1px)}',
      '.navbar button:disabled{opacity:.32;cursor:default}',
      '.navbar svg{width:17px;height:17px;display:block}',
      '.nav-counter{font-size:.92rem;color:var(--muted);font-variant-numeric:tabular-nums;min-width:54px;text-align:center}',
      '.counter-top{position:fixed;top:18px;right:24px;z-index:10;font-size:.95rem;color:var(--muted);',
      '  font-variant-numeric:tabular-nums;letter-spacing:.06em;opacity:.9}',
      (opt.nav.placement === 'tr' ? '.counter-top{top:78px}' : ''),
      /* ----- progress bar ----- */
      '.progress-rail{position:fixed;left:0;right:0;bottom:0;height:3px;z-index:9;background:color-mix(in srgb,var(--accent) 10%,transparent)}',
      '.progress-fill{height:100%;width:0;background:linear-gradient(90deg,var(--accent),var(--accent2));transition:width .35s ease;border-radius:0 3px 3px 0}',
      /* ----- notes ----- */
      hasNotes ? [
        '.notes-panel{position:fixed;left:50%;transform:translate(-50%,12px);bottom:84px;z-index:11;width:min(760px,90vw);',
        '  max-height:34vh;overflow:auto;background:color-mix(in srgb,var(--bg) 88%,black);border:1px solid color-mix(in srgb,var(--accent) 35%,transparent);',
        '  border-radius:14px;padding:18px 22px;box-shadow:0 18px 60px rgba(0,0,0,.5);opacity:0;pointer-events:none;transition:opacity .25s,transform .25s}',
        '.notes-panel.open{opacity:1;pointer-events:auto;transform:translate(-50%,0)}',
        '.notes-panel h4{font-size:.78rem;letter-spacing:.18em;text-transform:uppercase;color:var(--accent);margin-bottom:8px}',
        '.notes-panel p{font-size:.98rem;line-height:1.55;color:var(--text);white-space:pre-wrap}',
        '.notes-panel p.empty{color:var(--muted);font-style:italic}'
      ].join('\n') : '',
      /* ----- small screens ----- */
      '@media (max-width:760px){',
      '  .slide{padding:3vh 6vw}',
      '  .bullets li{font-size:1rem}',
      '  .navbar{gap:9px}',
      '  .counter-top{top:12px;right:14px;font-size:.85rem}',
      '  .corner{display:none}',
      '}',
      '@media (max-height:560px){.s-title .subtitle{margin-top:12px}.content{margin-top:16px}}'
    ].filter(Boolean).join('\n');
  }

  // ------------------------------------------------------------------- JS

  function engineJs(opt, hasCanvas, notesArr) {
    var hasNotes = !!notesArr;
    return [
      "(function(){",
      "'use strict';",
      "var slides=document.querySelectorAll('.slide');",
      "var total=slides.length,current=0;",
      "var cur=document.getElementById('cur'),tot=document.getElementById('total');",
      "var npCur=document.getElementById('np-cur'),npTot=document.getElementById('np-total');",
      "var prev=document.getElementById('prev'),next=document.getElementById('next');",
      "var fill=document.getElementById('progress-fill');",
      hasCanvas ? "var bg=document.getElementById('bg-canvas');" : "var bg=null;",
      "if(tot)tot.textContent=total;if(npTot)npTot.textContent=total;",
      hasNotes ? "var NOTES=" + JSON.stringify(notesArr).replace(/</g, '\\u003c') + ";" : "",
      hasNotes ? "var notesPanel=document.getElementById('notes-panel'),notesBody=document.getElementById('notes-body');" : "",
      "var animTimer=null;",
      "function showSlide(n){",
      "  if(n<0)n=0;if(n>=total)n=total-1;",
      "  for(var i=0;i<slides.length;i++){slides[i].classList.toggle('active',i===n);slides[i].classList.remove('anim');}",
      opt.transition !== 'none' ? [
        "  slides[n].classList.add('anim');",
        "  clearTimeout(animTimer);",
        "  animTimer=setTimeout(function(){slides[n].classList.remove('anim');},700);"
      ].join('\n') : "",
      "  current=n;",
      "  if(cur)cur.textContent=n+1;if(npCur)npCur.textContent=n+1;",
      "  if(prev)prev.disabled=n===0;if(next)next.disabled=n===total-1;",
      "  if(fill)fill.style.width=(total>1?(n/(total-1))*100:100)+'%';",
      "  if(bg){var mode=slides[n].getAttribute('data-bg')||'subtle';",
      "    bg.classList.toggle('feature',mode==='feature');",
      "    bg.classList.toggle('hidden',mode==='hidden');",
      "    bg.dataset.paused=mode==='hidden'?'1':'0';}",
      hasNotes ? "  if(notesBody){var t=NOTES[n];notesBody.textContent=t||'No notes for this slide.';notesBody.classList.toggle('empty',!t);}" : "",
      "}",
      "if(prev)prev.addEventListener('click',function(){showSlide(current-1)});",
      "if(next)next.addEventListener('click',function(){showSlide(current+1)});",
      "document.addEventListener('keydown',function(e){",
      "  if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();showSlide(current+1);}",
      "  else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();showSlide(current-1);}",
      "  else if(e.key==='Home'){e.preventDefault();showSlide(0);}",
      "  else if(e.key==='End'){e.preventDefault();showSlide(total-1);}",
      "  else if(e.key==='f'||e.key==='F'){",
      "    if(document.fullscreenElement)document.exitFullscreen();",
      "    else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen();}",
      hasNotes ? "  else if(e.key==='n'||e.key==='N'){notesPanel.classList.toggle('open');}" : "",
      "});",
      "var touchX=0;",
      "document.addEventListener('touchstart',function(e){touchX=e.touches[0].clientX;},{passive:true});",
      "document.addEventListener('touchend',function(e){",
      "  var diff=touchX-e.changedTouches[0].clientX;",
      "  if(Math.abs(diff)>50)showSlide(current+(diff>0?1:-1));",
      "},{passive:true});",
      "showSlide(0);",
      "})();"
    ].filter(Boolean).join('\n');
  }

  var ARROW_L = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="15 18 9 12 15 6"/></svg>';
  var ARROW_R = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="9 18 15 12 9 6"/></svg>';

  function navHtml(opt) {
    var prevInner = opt.nav.labels === 'words' ? ARROW_L + '<span>Prev</span>' : ARROW_L;
    var nextInner = opt.nav.labels === 'words' ? '<span>Next</span>' + ARROW_R : ARROW_R;
    var counter = opt.nav.showCounter
      ? '<span class="nav-counter"><span id="np-cur">1</span> / <span id="np-total">1</span></span>'
      : '';
    return '<nav class="navbar" aria-label="Slide navigation">' +
      '<button id="prev" aria-label="Previous slide">' + prevInner + '</button>' +
      counter +
      '<button id="next" aria-label="Next slide">' + nextInner + '</button>' +
      '</nav>';
  }

  // ----------------------------------------------------------------- build

  function build(content, options) {
    var opt = merge(DEFAULTS, options || {});
    var slides = content.slides || [];
    var faithful = (opt.mode === 'faithful' && content.faithful &&
      content.faithful.slides && content.faithful.slides.length) ? content.faithful : null;
    var slideCount = faithful ? faithful.slides.length : slides.length;
    var hasCanvas = opt.effect !== 'none' && global.Backgrounds && !!global.Backgrounds.source(opt.effect);

    // per-slide canvas visibility (faithful mode: first slide is the title)
    var dataBgs = [];
    for (var di = 0; di < slideCount; di++) {
      var isFeature = faithful
        ? di === 0
        : (slides[di].type === 'title' || slides[di].type === 'section');
      if (!hasCanvas) dataBgs.push('hidden');
      else if (opt.effectShow === 'all') dataBgs.push('feature');
      else if (opt.effectShow === 'title') dataBgs.push(isFeature ? 'feature' : 'hidden');
      else dataBgs.push(isFeature ? 'feature' : 'subtle'); // title-subtle
    }

    var notesArr = null;
    if (opt.includeNotes && slides.length === slideCount) {
      var any = slides.some(function (s) { return s.notes; });
      if (any) notesArr = slides.map(function (s) { return s.notes || ''; });
    }

    var parts = [];
    parts.push('<!DOCTYPE html>');
    parts.push('<html lang="en"><head>');
    parts.push('<meta charset="UTF-8">');
    parts.push('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
    parts.push('<title>' + esc(opt.title) + '</title>');
    parts.push('<style>' + css(opt, hasCanvas, !!notesArr) +
      (faithful ? '\n' + faithfulCss(faithful) : '') + '</style>');
    parts.push('</head><body>');

    if (hasCanvas) parts.push('<canvas id="bg-canvas"></canvas>');

    parts.push('<div class="deck">');
    if (faithful) {
      faithful.slides.forEach(function (sHtml, i) {
        parts.push('<section class="slide s-faithful' + (i === 0 ? ' active' : '') +
          '" data-bg="' + dataBgs[i] + '">' + sHtml + '</section>');
      });
    } else {
      slides.forEach(function (s, i) { parts.push(slideHtml(s, i, opt, dataBgs[i])); });
    }
    parts.push('</div>');

    if (opt.nav.showTopCounter) {
      parts.push('<div class="counter-top"><span id="cur">1</span> / <span id="total">1</span></div>');
    }
    parts.push(navHtml(opt));
    if (opt.progressBar) {
      parts.push('<div class="progress-rail"><div class="progress-fill" id="progress-fill"></div></div>');
    }
    if (notesArr) {
      parts.push('<div class="notes-panel" id="notes-panel"><h4>Speaker notes · press N to hide</h4><p id="notes-body"></p></div>');
    }

    parts.push('<script>');
    parts.push(engineJs(opt, hasCanvas, notesArr));
    if (faithful) parts.push(faithfulFitJs(faithful.slideSize));
    if (hasCanvas) {
      var bgConf = {
        accent: opt.theme.accent, accent2: opt.theme.accent2,
        text: opt.theme.text, bg: opt.theme.bg,
        intensity: opt.effectIntensity
      };
      parts.push('(' + global.Backgrounds.source(opt.effect) + ')(document.getElementById("bg-canvas"),' +
        JSON.stringify(bgConf) + ');');
    }
    parts.push('<\/script>');
    parts.push('</body></html>');
    return parts.join('\n');
  }

  global.DeckBuilder = { build: build, defaults: function () { return merge(DEFAULTS, {}); } };

})(window);
